### ISSUE TITLE
Add service cost in inbound sms request

### ISSUE THREAD

**Issue by ninsuo** [Nexmo/api-specification#135]
Hello,

I am developing [communication tools](https://github.com/redcall-io/front) for the Red Cross. Basically the app asks volunteer's availability when an event occur and they can answer directly to a virtual phone number. After a few minutes, ambulances are filled up with all the required skills.

We are tracking communication prices in order to input the budget of the unit which used the tool, but I noticed that quite recently(?), inbound SMS are paid (0.0057 cts in most countries, details in [the Nexmo pricing page](https://www.nexmo.com/pricing/).

When sending SMS, that's easy, we have a `message-price` field in the [response](https://developer.nexmo.com/api/sms). 

But the cost of inbound messages is not given in the [inbound sms requests](https://developer.nexmo.com/api/sms#inbound-sms). I may hardcode 0.0057 somewhere in the configuration, but It's a bad thing for 2 reasons : 

- Nexmo may change its pricing
- We may receive messages from abroad at different prices

Is it possible to add the cost information in the inbound sms request?

Have a great day!

**Comment by lornajane** [comment]
Thanks for getting in touch with us about this. We recently made the pricing change and the API change to match it isn't completed yet but it is on our roadmap. I'll close this issue since it's in progress elsewhere, but please bear with us and this change will appear in due course.

**Comment by ninsuo** [comment]
Thank you.
It could be a good idea though, to do the change on the API **before** on the pricing next time.
Currently it's a nightmare to give precise details about consumption.
