### ISSUE TITLE
Text-To-Speech-Prompt API is deprecated

### ISSUE THREAD

**Issue by carlos845** [Nexmo/api-specification#181]
Please remove **Text-To-Speech-Prompt API** from **message-id** query parameter.

**Comment by mheap** [comment]
@carlos845 Do you have any more details that you could share about this?

**Comment by carlos845** [comment]
Text-To-Speech-Prompt API is a deprecated product so it should be remove from the docs.

**Comment by mheap** [comment]
Thanks!
