### ISSUE TITLE
Standard search parameters for date/time filtering

### ISSUE THREAD

**Issue by nzmark** [Nexmo/api-specification#4]
Currently at Nexmo there are at least two ways to filter by date/time when searching for resources.
e.g. the reporting service https://nexmoinc.atlassian.net/wiki/display/EN/Reporting+Service uses from_date, _to_date
e.g. the media service https://nexmoinc.atlassian.net/wiki/display/EN/The+API uses start_date, end_date

Please define a standard set of parameters for temporal filtering that all v2 and later APIs must implement, to promote consistency of our public-facing APIs.

**Comment by lornajane** [comment]
Closing this as it's outdated - our API standards are here https://nexmo.github.io/api-standards/
