### ISSUE TITLE
SMS API response error codes are actually SMS delivery receipt error codes

### ISSUE THREAD

**Issue by LisaRoskam** [Nexmo/api-specification#48]
The error codes and explanations at https://developer.nexmo.com/api-errors/sms are _not_ Nexmo API response error codes. I actually can no longer find the SMS error API response error codes listed correctly anywhere in our docs. :(

Warning: https://developer.nexmo.com/api/sms#delivery-receipt err-code SMS Error reference link also points to https://developer.nexmo.com/api-errors/sms and the content is correct in this context.

SMS Delivery Receipt Error codes are also described in our Knowledgebase at https://help.nexmo.com/hc/en-us/articles/204014733

**Comment by lornajane** [comment]
Thanks @LisaRoskam ! This is very helpful and also very timely as @marklewin and I are in progress with an overhaul of the SMS docs.

**Comment by mheap** [comment]
This has been fixed, thanks @LisaRoskam 

https://developer.nexmo.com/messaging/sms/guides/troubleshooting-sms#sms-api-error-codes
