### ISSUE TITLE
Current Balance in Response

### ISSUE THREAD

**Issue by tjlytle** [Nexmo/api-specification#6]
Currently the SMS API returns a `remaining-balance` property on the request. It's not returned using the message search API because that has not meaning after the fact. 

As we try to define consistent resource structures data like this (only useful in the context of the 'transaction', not the resource that was created) should not be in the returned resource.

It's probably worth considering if adding this data to the response is needed (as a call to  `/accounts/:id/balance` provides the same); however, this transactional metadata could be returned in the header to keep the resource structure consistent.

On the balance specifically, with new billing models in the future seems this could be either the prepaid balance (which may be negative if allowed for the account) or the remaining MAU (whatever we end up calling it) for the month (which could also be negative if we allow it for the account).

At this point can we reach an agreement on exposing this kind of data in the headers and not in the response body?

**Comment by lornajane** [comment]
Closed due to inactivity
