### ISSUE TITLE
API standards for modifying resource

### ISSUE THREAD

**Issue by nzmark** [Nexmo/api-specification#7]
For the action of modifying an existing resource, should the API guidelines indicate how this is done?
- e.g. method must be PUT (vs POST, or both PUT and POST)
- e.g. PUT body _must_ include ALL of a representation vs PUT body _may_ include only modified fields (implies URI path is all that is needed to uniquely identify a specific resource);
- e.g. all resources _must_ include a last-modified timestamp, if a PUT operation attempts to change a resource but its timestamp is later than the server’s version of the resource, request is rejected with a 409

**Comment by lornajane** [comment]
This is outdated - the API standards guidelines are here https://nexmo.github.io/api-standards/
